- src/main/java/com/brennaswitzer/cookbook/graphql/LabelsQuery.java
- src/main/java/com/brennaswitzer/cookbook/graphql/Query.java
- src/main/resources/graphqls/labels.graphqls
Adds a fetch to get labels for autocomplete
> adds schema for get labels

- src/main/java/com/brennaswitzer/cookbook/graphql/model/OffsetConnection.java
- src/main/java/com/brennaswitzer/cookbook/repositories/SearchResponse.java
- src/main/java/com/brennaswitzer/cookbook/resolvers/RecipeResolver.java
- src/main/resources/graphqls/library.graphqls
Address a couple issues with the initial library schema:
1. empty photos
2. cursors on empty connection pages
3. `Ingredient.name` is non-nullable
4. `Recipe.totalTime` in minutes (not milliseconds) w/ ability to request another unit if desired.
> Graphql recipe search

- pom.xml
- src/main/java/com/brennaswitzer/cookbook/CookbookApplication.java
- src/main/java/com/brennaswitzer/cookbook/config/CalendarProperties.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlanBucket.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlanItem.java
- src/main/java/com/brennaswitzer/cookbook/repositories/PlanBucketRepository.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanCalendar.java
- src/main/java/com/brennaswitzer/cookbook/util/ShareHelper.java
- src/main/java/com/brennaswitzer/cookbook/util/SlugUtils.java
- src/main/java/com/brennaswitzer/cookbook/web/PlanController.java
- src/main/java/com/brennaswitzer/cookbook/web/RecipeController.java
- src/main/java/com/brennaswitzer/cookbook/web/SharedPlanController.java
- src/main/java/com/brennaswitzer/cookbook/web/SharedRecipeController.java
- src/main/resources/application.yml
- src/main/resources/db/changelog/foodinger-2023.sql
- src/test/java/com/brennaswitzer/cookbook/util/SlugUtilsTest.java
Add a secret-secured URL for getting a plan in iCalendar format, according to its dated buckets.
> plan as ical

- src/main/java/com/brennaswitzer/cookbook/payload/RecognizedRange.java
- src/test/java/com/brennaswitzer/cookbook/payload/RecognizedRangeTest.java
OBOBs _everywhere_! The ranges from 0-2 and from 2-4 do not overlap, they are adjacent.
> adjacent ranges don't count as overlapping

- src/main/java/com/brennaswitzer/cookbook/domain/Named.java
- src/main/java/com/brennaswitzer/cookbook/domain/PantryItem.java
- src/main/java/com/brennaswitzer/cookbook/repositories/PantryItemRepository.java
- src/main/java/com/brennaswitzer/cookbook/services/IngredientService.java
- src/main/java/com/brennaswitzer/cookbook/services/ItemService.java
- src/main/resources/db/changelog/gobrennas-2024.sql
- src/test/java/com/brennaswitzer/cookbook/domain/PantryItemTest.java
- src/test/java/com/brennaswitzer/cookbook/services/ItemServiceTest.java
- src/test/java/com/brennaswitzer/cookbook/util/RecipeBox.java
- src/test/resources/application-test.yml
add synonyms to pantry items' data model, as well as recog support. Can't _add_ synonyms yet, but that's coming.
> Pantry item synonyms

- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryQuery.java
- src/main/java/com/brennaswitzer/cookbook/repositories/RecipeSearchRepositoryImpl.java
- src/main/java/com/brennaswitzer/cookbook/repositories/impl/LibrarySearchRequest.java
- src/main/java/com/brennaswitzer/cookbook/resolvers/RecipeResolver.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/main/java/com/brennaswitzer/cookbook/web/RecipeController.java
- src/main/resources/graphqls/library.graphqls
Support searching for recipes by ingredient. Implemented as "any" at the moment, rather than "all", but that's subject to change.
Motivated by preview in the pantry admin, where it'll be a single ingredient, and thus any/all are equivalent.
> support recipe search by ingredient

- src/main/resources/graphqls/planner.graphqls
Adding the ingredient for reference to the planItem
> add ingredient to planItem

- src/main/resources/db/changelog/gobrennas-2024.sql
> remove the '--on-stage' label - we have plans now

- src/main/resources/public/import_bookmarklet.js
Updating the selectors for the nytimes
> update selectors for nytimes

- src/main/java/com/brennaswitzer/cookbook/domain/Rating.java
- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryMutation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/RecipeHistoryMutation.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeHistoryService.java
- src/main/resources/graphqls/library.graphqls
Add mutations for recipe history, supporting only setting a rating. And a ghastly kludge of some authorization. :|
> support setting ratings on recipe history

- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
When scaling a recipe onto the plan, track the scale factor, and then "un-scale" the planned recipe before diffing it with the library recipe.
closes #88
> Scaled recipe diffs

- src/main/java/com/brennaswitzer/cookbook/domain/PantryItemDuplicate.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlanBucket.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
- src/main/java/com/brennaswitzer/cookbook/web/PlanController.java
- src/test/java/com/brennaswitzer/cookbook/services/PlanServiceDbTest.java
- src/test/java/com/brennaswitzer/cookbook/services/PlanServiceMockedTest.java
When a plan's buckets change, that should cause them to sync across devices, just like plan items do.
closes #91 
**PS:** GitHub it _terrible_ at its job.
> buckets dont sync across devices

- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryQuery.java
- src/main/java/com/brennaswitzer/cookbook/graphql/model/OffsetConnectionCursor.java
- src/main/java/com/brennaswitzer/cookbook/graphql/model/SuggestionRequest.java
- src/main/java/com/brennaswitzer/cookbook/repositories/PlannedRecipeHistoryRepository.java
- src/main/java/com/brennaswitzer/cookbook/repositories/RecipeRepository.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/main/resources/db/changelog/gobrennas-2024.sql
- src/main/resources/graphqls/library.graphqls
GraphQL endpoint to return some ad hoc-computed suggestions for recipes the user is likely to want to cook.
> suggest recipes based on cook history

- src/main/java/com/brennaswitzer/cookbook/config/GraphQLConfig.java
- src/main/java/com/brennaswitzer/cookbook/graphql/Query.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/RecipeResolver.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/UserResolver.java
- src/main/java/com/brennaswitzer/cookbook/graphql/support/PrincipalUtil.java
- src/main/java/com/brennaswitzer/cookbook/security/CurrentUser.java
- src/main/java/com/brennaswitzer/cookbook/security/UserPrincipal.java
- src/main/java/com/brennaswitzer/cookbook/util/NoUserPrincipalException.java
- src/main/java/com/brennaswitzer/cookbook/util/UserPrincipalAccess.java
- src/main/java/com/brennaswitzer/cookbook/util/UserPrincipalAccessImpl.java
- src/main/resources/graphqls/profile.graphqls
Server support for https://github.com/folded-ear/gobrennas-client/issues/226 as well as reenabling introspection queries for unauthorized users.
> Profile from graphql

- src/main/java/com/brennaswitzer/cookbook/graphql/PantryQuery.java
- src/main/java/com/brennaswitzer/cookbook/graphql/PlannerQuery.java
- src/main/java/com/brennaswitzer/cookbook/graphql/ProfileQuery.java
- src/main/java/com/brennaswitzer/cookbook/graphql/Query.java
- src/main/java/com/brennaswitzer/cookbook/repositories/UserRepository.java
- src/main/java/com/brennaswitzer/cookbook/web/RecipeController.java
- src/main/resources/graphqls/favorites.graphqls
- src/main/resources/graphqls/labels.graphqls
- src/main/resources/graphqls/library.graphqls
- src/main/resources/graphqls/pantry.graphqls
- src/main/resources/graphqls/planner.graphqls
- src/main/resources/graphqls/profile.graphqls
- src/test/java/com/brennaswitzer/cookbook/graphql/PlannerQueryTest.java
A few extensions to the GraphQL schema to let the client move more of its calls, and thus have consistent string IDs for everything.
> String ids

- Dockerfile
- pom.xml
- src/main/java/com/brennaswitzer/cookbook/config/AppProperties.java
- src/main/java/com/brennaswitzer/cookbook/config/RestClientConfig.java
- src/main/java/com/brennaswitzer/cookbook/web/ImageProxy.java
- src/main/resources/application.yml
- src/main/resources/public/import_bookmarklet.js
The issue that caused revert are with firefox's cookie passing, not the graphql conversion. It doesn't work with the REST-y calls either. :/
> Unrevert cook this graphql

- src/main/java/com/brennaswitzer/cookbook/security/oauth2/OAuth2AuthenticationSuccessHandler.java
- src/main/resources/public/import_bookmarklet.js
Set FTOKEN on the base domain, accept a theme color, and use flexbox
> Cook this spiffs

- src/main/java/com/brennaswitzer/cookbook/web/StatusController.java
Here's hoping this will let the app container auto-restart when the DB can't be reached...
> add startup/liveness probes

- src/main/java/com/brennaswitzer/cookbook/services/ItemService.java
Filter out (and log) any ingredients with duplicate names when building recognition suggestions. Which ingredient makes it through is arbitrary - though stable - since there's no way for the user to differentiate.
> ensure recog suggestions are textually distinct

- .dockerignore
- .gitignore
- Dockerfile
- pom.xml
- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryMutationController.java
- src/main/java/com/brennaswitzer/cookbook/graphql/RecipeHistoryMutationController.java
- src/main/java/com/brennaswitzer/cookbook/graphql/instrumentation/GraphQLLoggingInstrumentation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/support/CachingPreparsedDocumentProvider.java
- src/main/java/com/brennaswitzer/cookbook/repositories/impl/LibrarySearchRequest.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanCalendar.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/main/resources/application-production.yml
- src/main/resources/application.yml
- src/main/resources/db/changelog/baseline.xml
Atop 3.3, add 3.4 and 3.5. This is what happens when I ignore upgrades for a few years. Sorry.
> Spring boot 3.5
