folded-ear/gobrennas-api

- .github/workflows/ci-cd.yaml
- Dockerfile
- README.md
- pom.xml
- src/main/java/com/brennaswitzer/cookbook/domain/CompoundQuantity.java
No more Beanstalk. Containers for test and deploy. CI for branches. Sweeping changes with confidence... GO GO GO!
> switch to Java 11 (from 1.8)

- src/main/java/com/brennaswitzer/cookbook/domain/Favorite.java
- src/main/java/com/brennaswitzer/cookbook/domain/FavoriteType.java
- src/main/java/com/brennaswitzer/cookbook/graphql/FavoriteMutation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/FavoriteQuery.java
- src/main/java/com/brennaswitzer/cookbook/graphql/Mutation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/Query.java
- src/main/java/com/brennaswitzer/cookbook/repositories/FavoriteRepository.java
- src/main/java/com/brennaswitzer/cookbook/repositories/RecipeSearchRepository.java
- src/main/java/com/brennaswitzer/cookbook/repositories/RecipeSearchRepositoryImpl.java
- src/main/java/com/brennaswitzer/cookbook/resolvers/FavoriteResolver.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/main/java/com/brennaswitzer/cookbook/services/favorites/FetchFavorites.java
- src/main/java/com/brennaswitzer/cookbook/services/favorites/UpdateFavorites.java
- src/main/resources/db/changelog/foodinger-2023.sql
- src/main/resources/graphqls/favorites.graphqls
- src/test/java/com/brennaswitzer/cookbook/repositories/RecipeSearchRepositoryImplTest.java
Create a new `Favorite` type and expose it via the GraphQL schema. 
The storage is generic, so it can be reused beyond just the library. Right
now it's only hooked up to Recipes.
> API bits for favorites subsystem

- src/main/java/com/brennaswitzer/cookbook/payload/Page.java
- src/main/java/com/brennaswitzer/cookbook/repositories/RecipeSearchRepository.java
- src/main/java/com/brennaswitzer/cookbook/repositories/RecipeSearchRepositoryImpl.java
- src/main/java/com/brennaswitzer/cookbook/repositories/SearchRequest.java
- src/main/java/com/brennaswitzer/cookbook/repositories/SearchResponse.java
- src/main/java/com/brennaswitzer/cookbook/repositories/impl/LibrarySearchRequest.java
- src/main/java/com/brennaswitzer/cookbook/repositories/impl/LibrarySearchScope.java
- src/main/java/com/brennaswitzer/cookbook/repositories/impl/SearchResponseImpl.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/main/java/com/brennaswitzer/cookbook/web/RecipeController.java
- src/test/java/com/brennaswitzer/cookbook/repositories/RecipeSearchRepositoryImplTest.java
Library search has used Spring Data's Pageable/Slice abstractions, but they
only support paging through, not arbitrary slices of a result. So change to
use an offset/limit style way of constrainting results, which can support the
same paging behavior, as well as the cursor-based behavior that Relay wants.
> Library offset paging

- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/main/java/com/brennaswitzer/cookbook/web/RecipeController.java
By default, recipes are added at scale=1 (no scaling), but can be scaled by any factor. Only the recipe's ingredients will be scaled onto the plan, any subrecipes will be left unscaled.
> accept a scaling factor when adding recipes to the plan

- src/main/java/com/brennaswitzer/cookbook/domain/IngredientRef.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
While the quantity is all the matters when scaling a ref, it may be represented in the raw string as well, so need to update that as well.
> when scaling, need to update raw as well as quantity

- src/main/java/com/brennaswitzer/cookbook/services/ItemService.java
- src/test/java/com/brennaswitzer/cookbook/services/ItemServiceTest.java
- src/test/java/com/brennaswitzer/cookbook/util/RawUtilsTest.java
Addresses #20's mis-parse of 'each' ingredients w/ a subsequent unit reference.
> only accept an implicit unit before the item

- src/main/java/com/brennaswitzer/cookbook/config/GraphQLConfig.java
- src/main/java/com/brennaswitzer/cookbook/domain/S3File.java
- src/main/java/com/brennaswitzer/cookbook/domain/Upload.java
- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryMutation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/Mutation.java
- src/main/java/com/brennaswitzer/cookbook/payload/IngredientInfo.java
- src/main/java/com/brennaswitzer/cookbook/services/LocalStorageService.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/main/java/com/brennaswitzer/cookbook/services/S3StorageService.java
- src/main/java/com/brennaswitzer/cookbook/services/StorageService.java
- src/main/java/com/brennaswitzer/cookbook/services/textract/TextractService.java
- src/main/java/com/brennaswitzer/cookbook/web/RecipeController.java
- src/main/resources/graphqls/__master.graphqls
- src/main/resources/graphqls/library.graphqls
- src/main/resources/graphqls/planner.graphqls
- src/test/java/com/brennaswitzer/cookbook/graphql/LibraryMutationTest.java
- src/test/java/com/brennaswitzer/cookbook/util/MockTest.java
support create/update/deleted of recipes via graphql
> Save recipe graphql

- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryQuery.java
- src/test/java/com/brennaswitzer/cookbook/graphql/LibraryQueryTest.java
In reference to https://github.com/folded-ear/gobrennas-client/issues/71 -- the 404 will only show now when an explicit error is thrown from the API. This PR adds a `NoResultException` which will trigger the `404` in the client.
> Throw an error when a recipe isn't found

- src/main/java/com/brennaswitzer/cookbook/domain/Item.java
- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryQuery.java
- src/main/java/com/brennaswitzer/cookbook/payload/RawIngredientDissection.java
- src/main/java/com/brennaswitzer/cookbook/payload/RecognitionSuggestion.java
- src/main/java/com/brennaswitzer/cookbook/payload/RecognizedItem.java
- src/main/java/com/brennaswitzer/cookbook/payload/RecognizedRange.java
- src/main/java/com/brennaswitzer/cookbook/payload/RecognizedRangeType.java
- src/main/java/com/brennaswitzer/cookbook/resolvers/RecognizedItemResolver.java
- src/main/java/com/brennaswitzer/cookbook/services/ItemService.java
- src/main/java/com/brennaswitzer/cookbook/web/ItemController.java
- src/main/resources/graphqls/library.graphqls
- src/test/java/com/brennaswitzer/cookbook/graphql/LibraryQueryTest.java
- src/test/java/com/brennaswitzer/cookbook/payload/RecognizedItemTest.java
- src/test/java/com/brennaswitzer/cookbook/services/ItemServiceTest.java
- src/test/resources/raw/dissections.txt
Add a new field to `LibraryQuery` for recognizing an item. Finish standardizing on "quantity" (not "amount"). Move `RecognizedItem`'s nested types to the top level, to simplify java-graphql-kickstart configuration, as more of it can be done by auto-configuration. Split suggestion generation from the main item recognition, as GraphQL offers a way to talk about the two parts separately.
> Support item recognition via the GraphQL API

- Dockerfile
- pom.xml
Try a layered docker image, as well as running the app directly (without JarLauncher). The former should make for smaller images, due to layer reuse. The latter should make startup faster.
> Docker layers

- src/main/java/com/brennaswitzer/cookbook/domain/S3File.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/test/java/com/brennaswitzer/cookbook/domain/S3FileTest.java
- src/test/java/com/brennaswitzer/cookbook/services/RecipeServiceTest.java
I didn't do the graphql-ification of recipe stuff very well. The files work, but only the main happy path. Now there are a) some tests, and b) working aux paths.
closes #32 and #37
> edit recipe w/o a new photo clears existing photo

- src/main/java/com/brennaswitzer/cookbook/repositories/PostgresFullTextQueryConverter.java
- src/test/java/com/brennaswitzer/cookbook/repositories/PostgresFullTextQueryConverterTest.java
For unquoted search terms, use prefix matching. So `chi` will match `chicken`. It's not the  same as a `LIKE '%chi%'`, in that it's still using the stemmed indexed lexemes to match on, and it's prefix-only. More concretely, `chi` will _not_ match `enchiladas`, because the search is not a prefix as it is with `chicken`. So better, but perhaps not sufficient.
> use prefix matching for unquoted search terms

- src/main/java/com/brennaswitzer/cookbook/domain/Ingredient.java
- src/main/java/com/brennaswitzer/cookbook/domain/LabelRef.java
- src/main/java/com/brennaswitzer/cookbook/domain/PantryItem.java
- src/main/java/com/brennaswitzer/cookbook/domain/PantryItemDuplicate.java
- src/main/java/com/brennaswitzer/cookbook/graphql/PantryQuery.java
- src/main/java/com/brennaswitzer/cookbook/graphql/loaders/PantryItemDuplicateCountBatchLoader.java
- src/main/java/com/brennaswitzer/cookbook/graphql/model/OffsetConnection.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/PantryItemResolver.java
- src/main/java/com/brennaswitzer/cookbook/repositories/PantryItemSearchRepository.java
- src/main/java/com/brennaswitzer/cookbook/repositories/PantryItemSearchRepositoryImpl.java
- src/main/java/com/brennaswitzer/cookbook/repositories/SearchResponse.java
- src/main/java/com/brennaswitzer/cookbook/repositories/impl/PantryItemSearchRequest.java
- src/main/java/com/brennaswitzer/cookbook/services/PantryItemService.java
- src/main/java/com/brennaswitzer/cookbook/services/async/QueueProcessor.java
- src/main/java/com/brennaswitzer/cookbook/services/indexing/EventHandlerSlot.java
- src/main/java/com/brennaswitzer/cookbook/services/indexing/IngredientFulltextIndexer.java
- src/main/java/com/brennaswitzer/cookbook/services/indexing/IngredientNeedsReindexing.java
- src/main/java/com/brennaswitzer/cookbook/services/indexing/IngredientReindexQueueService.java
- src/main/java/com/brennaswitzer/cookbook/services/indexing/PantryItemNeedsDuplicatesFound.java
- src/main/java/com/brennaswitzer/cookbook/services/indexing/QueueProcessor.java
- src/main/java/com/brennaswitzer/cookbook/services/indexing/RefreshPantryItemDuplicates.java
- src/main/java/com/brennaswitzer/cookbook/services/indexing/ReindexIngredientEvent.java
- src/main/java/com/brennaswitzer/cookbook/services/indexing/ReindexIngredients.java
- src/main/resources/graphqls/pantry.graphqls
- src/test/java/com/brennaswitzer/cookbook/repositories/PantryItemSearchRepositoryImplTest.java
- src/test/java/com/brennaswitzer/cookbook/repositories/RecipeSearchRepositoryImplTest.java
- src/test/java/com/brennaswitzer/cookbook/services/indexing/IngredientIndexSmokeTest.java
- src/test/java/com/brennaswitzer/cookbook/services/indexing/IngredientReindexQueueServiceTest.java
- src/test/java/com/brennaswitzer/cookbook/util/RecipeBox.java
Expose duplicate pantry item info through the graphql interface, both counts and searching "duplicates of" an item. Right now, it's only 'tight' duplicates, meaning those which match full names/synonym, to reduce noise. So "cabbage" will consider "red cabbage" a duplicate, but not the converse.
Tracking of 'loose' duplicates, which do sub-matching, is in place but not exposed. When that's turned on "red cabbage" will consider both "cabbage" _and_ "red onion" as duplicates. All 'tight' duplicates are also 'loose' duplicates. From a Feb '23 dump of prod, there are about 2100 'tight' dupes, and another 6300 'loose' dupes. Note that those counts are bidirectional, so three identically-named items will express six dupes, and five such items will express twenty (`n * (n-1)`).
> Graphql item dupes

- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/RecipeResolver.java
Unlike planned recipes, two references to a library recipe are necessarily identical. So if a given recipe appears twice in a given recipe's "descendants", only return one copy in the recipe's subrecipes.
> when resolving subrecipes, only return a given recipe once

- src/main/java/com/brennaswitzer/cookbook/domain/BaseEntity.java
- src/main/java/com/brennaswitzer/cookbook/domain/InventoryItem.java
- src/main/java/com/brennaswitzer/cookbook/domain/PantryItemDuplicate.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlanItem.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlanItemStatus.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlannedRecipeHistory.java
- src/main/java/com/brennaswitzer/cookbook/domain/Recipe.java
- src/main/java/com/brennaswitzer/cookbook/repositories/PlannedRecipeHistoryRepository.java
- src/main/java/com/brennaswitzer/cookbook/services/EmptyTrashBins.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
- src/main/resources/db/changelog/gobrennas-2024.sql
- src/test/java/com/brennaswitzer/cookbook/services/PlanServiceTest.java
When a recipe is removed from a plan, record its add/remove timestamps and final status in a new `PlannedRecipeHistory` entity, instances of which are owned by the recipe itself.
> Cook planned stuff

- src/main/java/com/brennaswitzer/cookbook/domain/Plan.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlanItem.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlannedRecipeHistory.java
- src/main/java/com/brennaswitzer/cookbook/domain/Rating.java
- src/main/java/com/brennaswitzer/cookbook/domain/Recipe.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/PlannedRecipeHistoryResolver.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/RecipeResolver.java
- src/main/java/com/brennaswitzer/cookbook/repositories/RatingConverter.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
- src/main/resources/db/changelog/gobrennas-2024.sql
- src/main/resources/graphqls/library.graphqls
- src/test/java/com/brennaswitzer/cookbook/services/PlanServiceTest.java
Offer planner history for recipes via graphql. Currently all in-memory processing, which should be fine for a while. In a couple years we'll need to revisit, as The Standard will have a few hundred items, and that's silly to pull into memory just to sort it and keep five.
> Planned recipe history

- src/main/java/com/brennaswitzer/cookbook/domain/Acl.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlanBucket.java
- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryMutation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/PantryMutation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/PlannerMutation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/TimerMutation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/model/Deletion.java
- src/main/java/com/brennaswitzer/cookbook/repositories/PantryItemRepository.java
- src/main/java/com/brennaswitzer/cookbook/services/PantryItemService.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/main/java/com/brennaswitzer/cookbook/services/timers/UpdateTimers.java
- src/main/java/com/brennaswitzer/cookbook/web/PlanController.java
- src/main/resources/graphqls/__master.graphqls
- src/main/resources/graphqls/library.graphqls
- src/main/resources/graphqls/pantry.graphqls
- src/main/resources/graphqls/planner.graphqls
- src/main/resources/graphqls/timers.graphqls
- src/test/java/com/brennaswitzer/cookbook/domain/AclTest.java
- src/test/java/com/brennaswitzer/cookbook/graphql/LibraryMutationTest.java
- src/test/java/com/brennaswitzer/cookbook/graphql/PlannerMutationTest.java
- src/test/java/com/brennaswitzer/cookbook/services/PlanServiceTest.java
When deleting something through apollo, the object must be manually evicted from the cache. The update function to do that is passed to `useMutation`, and doesn't have access to the variables passed to the invocation of the mutation. So have to return the now-deleted ID as part of the mutation's selection set, for the update function to use.
> new Deletion type for graphql deletions, so apollo can get the ID

- src/main/java/com/brennaswitzer/cookbook/web/SharedPlanController.java
curl now says `Content-Type: text/calendar; charset=UTF-8` is coming out of boot. Hopefully cloud run won't mess with it. :/
> put the right content type on the iCalendar plan

- src/main/java/com/brennaswitzer/cookbook/domain/User.java
- src/main/java/com/brennaswitzer/cookbook/graphql/loaders/RecipeIsFavoriteBatchLoader.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/RecipeResolver.java
- src/main/java/com/brennaswitzer/cookbook/repositories/FavoriteRepository.java
- src/main/java/com/brennaswitzer/cookbook/services/favorites/FetchFavorites.java
- src/test/java/com/brennaswitzer/cookbook/graphql/loaders/RecipeIsFavoriteBatchLoaderTest.java
When performing library search, batch load "is favorite" instead of doing it recipe-by-recipe. While fav status is currently used for ordering results, I opted not to try and weave it into memory to avoid requerying as I did for pantry item use/dupe counts. Recipe search is going to evolve, since it's actually _search_ instead of just a listing, so opted to leave it simpler.
> batch-load favorites for library search

- src/main/java/com/brennaswitzer/cookbook/graphql/PlannerMutation.java
- src/main/resources/graphqls/planner.graphqls
- src/test/java/com/brennaswitzer/cookbook/graphql/PlannerMutationTest.java
"Duplicate plan" was already present via a separate mutation, but that makes the client awkward. Add the ability to create by duplication, retaining create blank.
Closes #69
> support create-from-source as well as create-blank and duplicate

- src/main/java/com/brennaswitzer/cookbook/graphql/PlannerMutation.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
- src/main/resources/graphqls/planner.graphqls
- src/test/java/com/brennaswitzer/cookbook/graphql/PlannerMutationTest.java
- src/test/java/com/brennaswitzer/cookbook/services/PlanServiceTest.java
This adds an optional `doneAt` Date scalar to the `setStatus` mutation on the planner. This piece of data will allow us to "complete" a recipe on a day that is not today. Which, as it turns out, is kind of a thing for me.
To test out the mutation:
```
mutation setStatus($id: ID!, $status: PlanItemStatus!, $doneAt: Date) {
planner {
setStatus(id: $id, status: $status, doneAt: $doneAt) {
id
}
}
}
```
> add doneAt date to setStatus mutation

- src/main/java/com/brennaswitzer/cookbook/services/EmptyTrashBins.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanCalendar.java
- src/main/java/com/brennaswitzer/cookbook/web/SharedPlanController.java
Keep the trash around for 30 days (vs seven), allow pulling a plain-text calendar, and explicitly use UTC instead of relying on the system default.
> Calendar spiffs

- src/main/java/com/brennaswitzer/cookbook/domain/Quantity.java
- src/main/java/com/brennaswitzer/cookbook/graphql/loaders/UnitOfMeasureBatchLoader.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/QuantityResolver.java
- src/main/java/com/brennaswitzer/cookbook/repositories/UnitOfMeasureRepository.java
Instead of letting Hibernate lazy-load `UnitOfMeasure`s one at a time off `Quantity` fields, collect the IDs and batch load them.
> batch load units for graphql queries

- src/main/java/com/brennaswitzer/cookbook/services/ItemService.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
Plan items whose names start with a bang will never be recognized as an ingredient, and if they have a reference (e.g., a library recipe sent to plan) it will be stripped.
closes #86
> plan items whose names start with a bang are excluded from ingredient recognition

- src/main/java/com/brennaswitzer/cookbook/domain/Photo.java
- src/main/java/com/brennaswitzer/cookbook/domain/Recipe.java
- src/main/java/com/brennaswitzer/cookbook/domain/S3File.java
- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryMutation.java
- src/main/java/com/brennaswitzer/cookbook/services/LocalStorageService.java
- src/main/java/com/brennaswitzer/cookbook/services/RecipeService.java
- src/main/java/com/brennaswitzer/cookbook/services/S3StorageService.java
- src/main/java/com/brennaswitzer/cookbook/services/StorageService.java
- src/main/resources/graphqls/library.graphqls
- src/test/java/com/brennaswitzer/cookbook/graphql/LibraryMutationTest.java
Allow creating a new recipe to indicate a source recipe it was copied from, and if the new recipe doesn't supply a photo, copy the source recipe's photo (if it has one).
> Include photo on copy

- src/main/java/com/brennaswitzer/cookbook/domain/Plan.java
- src/main/java/com/brennaswitzer/cookbook/graphql/PlannerMutation.java
- src/main/java/com/brennaswitzer/cookbook/payload/PlanItemInfo.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
- src/main/java/com/brennaswitzer/cookbook/web/PlanController.java
- src/main/resources/db/changelog/gobrennas-2024.sql
- src/main/resources/graphqls/planner.graphqls
- src/test/java/com/brennaswitzer/cookbook/services/PlanServiceMockedTest.java
Plans carry an explicit color, which may be null. If unset, a color stably computed from the `eq_key` will be used, so it can cross the persistence boundary. The same options are used as the client, but the hash function is different, so the effective mapping will also differ.
> support a String-typed color property on Plan

- .gitignore
- src/main/java/com/brennaswitzer/cookbook/domain/CorePlanItem.java
- src/main/java/com/brennaswitzer/cookbook/domain/PlanItem.java
- src/main/java/com/brennaswitzer/cookbook/domain/Recipe.java
- src/main/java/com/brennaswitzer/cookbook/graphql/PlannerMutation.java
- src/main/java/com/brennaswitzer/cookbook/graphql/PlannerQuery.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/PlanItemResolver.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/PlanResolver.java
- src/main/java/com/brennaswitzer/cookbook/graphql/resolvers/RecipeResolver.java
- src/main/java/com/brennaswitzer/cookbook/payload/PlanItemInfo.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanService.java
- src/main/java/com/brennaswitzer/cookbook/web/SharedRecipeController.java
- src/main/resources/graphqls/planner.graphqls
- src/main/resources/graphqls/profile.graphqls
- src/test/java/com/brennaswitzer/cookbook/graphql/PlannerMutationTest.java
- src/test/java/com/brennaswitzer/cookbook/graphql/PlannerQueryTest.java
- src/test/java/com/brennaswitzer/cookbook/graphql/resolvers/PlanItemResolverTest.java
Machinations to support synchronizing plans via GraphQL, instead of REST. Most of it is type shenanigans to support kickstart's runtime-reflection-based behavior. The only meaningful change is making ACE's user/grant fields non-nullable. That's how they should have been from the start, but I didn't notice until now.
> GraphQL plan synchronizer

- src/main/java/com/brennaswitzer/cookbook/services/PlanCalendar.java
- src/main/java/com/brennaswitzer/cookbook/web/SharedPlanController.java
When a recipe is planned, bucketed, and deleted w/in six hours, don't include it on the plan's calendar. The assumption is that such recipes are ephemeral artifacts of making a plan, not actually planned recipes.
> on plan calendars, don't include recipes deleted w/in six hours of being planned

- src/main/java/com/brennaswitzer/cookbook/graphql/instrumentation/GraphQLLoggingInstrumentation.java
Normal access logging is useless for GraphQL requests, so roll some custom logging. Exceptions get logged at `ERROR`, GraphQL errors at `WARN`, operation name and execution time at `INFO`, and the query, variables, and result data at `DEBUG`. All lines have an `executionId` (a UUID) for correlation. Two pristine requests w/ `DEBUG` enabled:
```
2025-01-25T14:43:57.252-08:00 DEBUG 65083 --- [  XNIO-1 task-2] c.b.c.g.i.GraphQLLoggingInstrumentation  : graphql 64946b0a-111b-4e44-b6fe-a549708752e1 query: "query listAllFavorites {\n  favorite {\n    all {\n      id\n      objectType\n      objectId\n      __typename\n    }\n    __typename\n  }\n}"
2025-01-25T14:43:57.252-08:00 DEBUG 65083 --- [  XNIO-1 task-2] c.b.c.g.i.GraphQLLoggingInstrumentation  : graphql …
```
> add a logging instrumentation to GraphQL processing

- src/main/java/com/brennaswitzer/cookbook/graphql/LibraryQuery.java
- src/main/java/com/brennaswitzer/cookbook/graphql/PantryQuery.java
- src/main/java/com/brennaswitzer/cookbook/services/IngredientService.java
- src/main/resources/graphqls/library.graphqls
- src/main/resources/graphqls/pantry.graphqls
The query behaves like the `bulk-ingredients` endpoint, returning a heterogeneous collection of `Ingredients`. Ingredients don't have their own slice of the GraphQL Query, so opted to put equivalent fields on both sides.
> add a query for bulk ingredients to pantry/library

- Dockerfile
- src/main/resources/application.yml
Setting up [CDS](https://docs.spring.io/spring-framework/reference/integration/cds.html) adds an extra ~130MB layer to the image, but reduces startup time by about 50% on my local. Depending on how you ask, it either makes no difference to memory consumption or reduces it slightly. We'll see how GCP measures when it's deployed. :)
The Temurin I have didn't come with the system archive, but the base image has it. So didn't regen it for our image like I did locally.
> set up CDS for the prod image

- src/main/java/com/brennaswitzer/cookbook/config/AppProperties.java
- src/main/java/com/brennaswitzer/cookbook/config/CalendarProperties.java
- src/main/java/com/brennaswitzer/cookbook/services/EmptyTrashBins.java
- src/main/java/com/brennaswitzer/cookbook/services/PlanCalendar.java
When an item is deleted within a dated bucket, don't cancel its calendar event until it has been in the trash a while. Unless it was deleted soon after creation, implying it was tentatively planned and then rejected.
This keeps the calendar projection of a plan intact for "a while", even as planned recipes are completed (or deleted) over the duration of executing the plan. The "while" lasts until the plan's buckets are updated/reset, capped at two weeks.
> don't cancel calendar events upon item delete
